name: Sync Upstream

permissions:
  contents: write
  issues: write
  actions: write

on:
  schedule:
    - cron: "10 */1 * * *" # 每小时执行
  workflow_dispatch: # 手动触发

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - uses: actions/checkout@v4

      - name: Clean issue notice
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          labels: "🚨 Sync Fail"

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: vbenjs/vue-vben-admin
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-issue"
          title: "🚨 同步失败 | Sync Fail"
          labels: "🚨 Sync Fail"
          body: |
            由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次。
